apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      name: client-pods
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: 6131305010/gin-azblob:v1

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: client-service
# spec:
#   type: NodePort
#   selector:
#     app: client
#   ports:
#   - port: 8080
    
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: client-service
# spec:
#   type: ClusterIP
#   selector:
#     app: client
#   ports:
#   - port: 8080
  
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: myingress
#   annotations:
#     kubernetes.io/ingress.class: addon-http-application-routing
# spec:
#   rules:
#     - http:
#         paths:
#           - pathType: Prefix
#             path: "/"
#             backend:
#               service:
#                 name: client-service
#                 port: 
#                   number: 8080


--- 
apiVersion: v1
kind: Service
metadata:
  name: app-lb
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
  - port: 8080
